spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      open-in-view: false
